import animTools.core as wh

wh.hotkey('w').setup('wh.ManipMode().translateModePress()')
wh.hotkey('w', release=True).setup('wh.ManipMode().translateModeRelease()')
wh.hotkey('e').setup('wh.ManipMode().rotateModePress()')
wh.hotkey('e', release=True).setup('wh.ManipMode().rotateModeRelease()')
wh.hotkey('r').setup('wh.ManipMode().scaleModePress()')
wh.hotkey('r', release=True).setup('wh.ManipMode().scaleModeRelease()')
wh.hotkey('g').setup('wh.KeyFrames().initialize()')
wh.hotkey(',').setup('wh.CurrentTime().prevFrame()')
wh.hotkey('.').setup('wh.CurrentTime().nextFrame()')
wh.hotkey(',', alt=True).setup('wh.CurrentTime().prevKey()')
wh.hotkey('.', alt=True).setup('wh.CurrentTime().nextKey()')
wh.hotkey('d', ctl=True, alt=True).setup('snapMe pivot', name='snapme_pivot', sourceType='mel')
wh.hotkey('w', ctl=True, alt=True).setup('snapMe position', name='snapme_position', sourceType='mel')
wh.hotkey('e', ctl=True, alt=True).setup('snapMe rotation', name='snapme_rotation', sourceType='mel')
wh.hotkey('r', ctl=True, alt=True).setup('snapMe scale', name='snapme_scale', sourceType='mel')

    # Display Hotkeys
wh.hotkey('D', ctl=True).setup('wh.ModelVis().deformers()')
wh.hotkey('G', ctl=True).setup('wh.ModelVis().grid()')
wh.hotkey('I', ctl=True).setup('wh.ModelVis().isolateSelect()')
wh.hotkey('J', ctl=True).setup('wh.ModelVis().joints()')
wh.hotkey('L', ctl=True).setup('wh.ModelVis().locators()')
wh.hotkey('C', ctl=True).setup('wh.ModelVis().nurbsCurves()')
wh.hotkey('N', ctl=True).setup('wh.ModelVis().nurbsSurfaces()')
wh.hotkey('P', ctl=True).setup('wh.ModelVis().polygons()')
wh.hotkey('W', ctl=True).setup('wh.ModelVis().wireframeOnShaded()')
wh.hotkey('X', ctl=True).setup('wh.ModelVis().xRay()')
wh.hotkey('Z', ctl=True).setup('wh.ModelVis().xRayJoints()')
wh.hotkey('A', alt=True).setupHotkey('AttributeEditor')
wh.hotkey('C', alt=True).setupHotkey('ConnectionEditor')
wh.hotkey('G', alt=True).setupHotkey('GraphEditor')
wh.hotkey('H', alt=True).setupHotkey('HypergraphHierarchyWindow')
wh.hotkey('P', ctl=True, alt=True).setupHotkey('PlayblastOptions')
wh.hotkey('H', ctl=True, alt=True).setupHotkey('HypergraphDGWindow')
wh.hotkey('H', ctl=True, alt=True, cmd=True).setupHotkey('HotkeyPreferencesWindow')
wh.hotkey('H', alt=True, cmd=True).setupHotkey('HypershadeWindow')
wh.hotkey('O', alt=True).setupHotkey('OutlinerWindow')
wh.hotkey('P', alt=True).setupHotkey('PlayblastWindow')
wh.hotkey('R', alt=True).setupHotkey('RenderViewWindow')
wh.hotkey('S', alt=True).setupHotkey('ScriptEditor')
wh.hotkey('T', alt=True).setupHotkey('ToolSettingsWindow')
wh.hotkey('Space', ctl=True).setup('abToggleUIVis', sourceType='mel')
