from wh.core.general.hotkey import *

hotkey('w').setup('whToggleTranslateModePress')
hotkey('w', release=True).setup('whToggleTranslateModeRelease')
hotkey('e').setup('whToggleRotateModePress')
hotkey('e', release=True).setup('whToggleRotateModeRelease')
hotkey('r').setup('whToggleScaleModePress')
hotkey('r', release=True).setup('whToggleScaleModeRelease')
hotkey('g').setup('whInitialize')
hotkey(',').setup('whPreviousFrame')
hotkey('.').setup('whNextFrame')
hotkey(',', alt=True).setup('whPreviousKey')
hotkey('.', alt=True).setup('whNextKey')
hotkey('d', ctl=True, alt=True).setup('snapMe pivot', name='snapme_pivot')
hotkey('w', ctl=True, alt=True).setup('snapMe position', name='snapme_position')
hotkey('e', ctl=True, alt=True).setup('snapMe rotation', name='snapme_rotation')
hotkey('r', ctl=True, alt=True).setup('snapMe scale', name='snapme_scale')

# Display Hotkeys

hotkey('D', ctl=True).setup('whToggleDeformers')
hotkey('G', ctl=True).setup('whToggleGrid')
hotkey('I', ctl=True).setup('whToggleIsolateSelect')
hotkey('J', ctl=True).setup('whToggleJoints')
hotkey('L', ctl=True).setup('whToggleLocators')
hotkey('C', ctl=True).setup('whToggleNurbsCurves')
hotkey('N', ctl=True).setup('whToggleNurbsSurfaces')
hotkey('P', ctl=True).setup('whTogglePolygons')
hotkey('W', ctl=True).setup('whToggleWireframeOnShaded')
hotkey('X', ctl=True).setup('whToggleXRay')
hotkey('Z', ctl=True).setup('whToggleXRayJoints')
hotkey('A', alt=True).setupHotkey('AttributeEditor')
hotkey('C', alt=True).setupHotkey('ConnectionEditor')
hotkey('G', alt=True).setupHotkey('GraphEditor')
hotkey('H', alt=True).setupHotkey('HypergraphHierarchyWindow')
hotkey('P', ctl=True, alt=True).setupHotkey('PlayblastOptions')
hotkey('H', ctl=True, alt=True).setupHotkey('HypergraphDGWindow')
hotkey('H', ctl=True, alt=True, cmd=True).setupHotkey('HotkeyPreferencesWindow')
hotkey('H', alt=True, cmd=True).setupHotkey('HypershadeWindow')
hotkey('O', alt=True).setupHotkey('OutlinerWindow')
hotkey('P', alt=True).setupHotkey('PlayblastWindow')
hotkey('R', alt=True).setupHotkey('RenderViewWindow')
hotkey('S', alt=True).setupHotkey('ScriptEditor')
hotkey('T', alt=True).setupHotkey('ToolSettingsWindow')
hotkey('Space', alt=True).setup('abToggleUIVis')
